### ISSUE TITLE
please add a Dockerfile

### ISSUE THREAD

**Issue by vanhauser-thc** [PLSysSec/sys#12]
I spend some time to build this and it is quite a hassle especially for the boolector part.
For future use - could you supply a Dockerfile? That would make using this much easier :)

**Comment by deian** [comment]
Sounds like a boolector issue :)

Neither one of us uses Docker and we don't plan to, but we're happy to integrate patches from the community. Happily, @rpw already added created a Docker file in https://github.com/PLSysSec/sys/issues/9. I've included it in the [the tree](https://github.com/PLSysSec/sys/blob/master/community/Dockerfile) in 821c4d7cf924e68838c128cbe824be46c9955416.
