### ISSUE TITLE
bad detect heapoob bug

### ISSUE THREAD

**Issue by maldiohead** [PLSysSec/sys#13]
hello, I use the follow code to test the ability of heapoob ,but it is not detected

int main()
{
int a;
char* ptr=malloc(1000);
ptr[2000]=0xa;
int b=a+10;
return b;
}

**Comment by deian** [comment]
The checker we implemented (and describe in the paper) won't catch these kinds of heap oob bugs, unfortunately. You'd have to either modify the checker. (If you do, please just name it something else we'd be happy to merge it in!)
