### ISSUE TITLE
Is it architecture independent?

### ISSUE THREAD

**Issue by ghost** [PLSysSec/sys#18]
Working on project where I got the ll (assembly language format files) files for arm architecture.

Will it also work on it?

Do I have to specify some extra flags? 

I think it is architecture independent, but got some errors like below:
```
DecodeException "Unknown DW_OP 4097"
DecodeException "Unknown DW_OP 148" 
```

Thanks,

**Comment by deian** [comment]
it works on llvm. that's a llvm-hs problem, see some of the closed issues.
