### ISSUE TITLE
BC (bitcode) or LL (LLVM assembly language format)

### ISSUE THREAD

**Issue by ghost** [PLSysSec/sys#20]
In the Readme Run section you use LL files as inputs.

Does it support BC and LL files as input? Or only LL?

Does it make a difference from performance, memory usage to have one big LL file/BC file or numerous BC/LL files?

What are the best practices, best approach?

Thanks,

**Comment by deian** [comment]
I think llvm-hs works happily with bc, but right now the front end is just looking for .ll extensions. Should be easy enough to extend.
