### ISSUE TITLE
Timed out when perform the uninit check

### ISSUE THREAD

**Issue by pcy190** [PLSysSec/sys#25]
I run the `sys` with the uninit check:
```
stack exec sys -- -c uninit -e prod -d ./compile_out/
```
However, after a long while, it failed with the timed out error:
```
Timed out
CallStack (from HasCallStack):
  error, called at src/Symex/Symex/Boolector.hs:242:18 in adverse-0.0.0.1-8OpQWnI8CptBIFknhXSwPz:Symex.Symex.Boolector
Timed out
CallStack (from HasCallStack):
  error, called at src/Symex/Symex/Boolector.hs:242:18 in adverse-0.0.0.1-8OpQWnI8CptBIFknhXSwPz:Symex.Symex.Boolector
Timed out
CallStack (from HasCallStack):
  error, called at src/Symex/Symex/Boolector.hs:242:18 in adverse-0.0.0.1-8OpQWnI8CptBIFknhXSwPz:Symex.Symex.Boolector
```
I wonder whether there is an option or modification of code to change the default time for solver to solve the constraint, in order to avoid the timed out case.

**Comment by deian** [comment]
Yep! https://github.com/PLSysSec/sys/blob/821c4d7cf924e68838c128cbe824be46c9955416/src/Checkers/SymexConfigs/CheckerConfigs.hs#L61

**Comment by deian** [comment]
We should make the cli more friendly #26
