### ISSUE TITLE
build the project failed 

### ISSUE THREAD

**Issue by maldiohead** [PLSysSec/sys#8]
after install the dependencies ；
and run the command: git checkout cleanup
an error occur:

![image](https://user-images.githubusercontent.com/23315692/90757336-189ac700-e310-11ea-9cce-0fc531a80ea8.png)

**Comment by mlfbrown** [comment]
Apologies for the outdated build instructions. Let me know how it works for you now, just building on master

**Comment by maldiohead** [comment]
can't find libLLVM-9.0 ,but I have install llvm 9.... what's the problem?
![image](https://user-images.githubusercontent.com/23315692/91790003-579b1780-ec42-11ea-9565-babd02b8bf8e.png)

**Comment by deian** [comment]
That seems like a llvm-hs problem. Can you try building llvm-hs standalone? My guess is that your llvm-config (which llvm-hs uses) is pointing to the wrong version.

**Comment by maldiohead** [comment]
lol. been solved ！ I know what's the problem, need install llvm-9-tools
