### ISSUE TITLE
LLVM 8 listed as dependency but LLVM 9 used

### ISSUE THREAD

**Issue by rpw** [PLSysSec/sys#9]
Hi,

the ``README.md`` claims that llvm-8 is a dependency for building sys. In fact from looking at ``stack.yaml`` it becomes clear that LLVM 9 is needed (the llvm-hs dependencies are all for LLVM 9).

Also, I've whipped up a Dockerfile -- based on Debian testing -- that can be used to effortlessly build a working version of sys:

https://gist.github.com/rpw/289afe7d01fb82533f7a839c8e1689bd

Feel free to integrate if you find it suitable.

**Comment by mlfbrown** [comment]
Thanks so much for the report! I've updated the readme and will take a look at integrating the Dockerfile today or tomorrow. Thanks a ton!

**Comment by deian** [comment]
Merged in 821c4d7cf924e68838c128cbe824be46c9955416 I added a trailing `>` to `MAINTAINER` line. Thanks so much!
